### ISSUE TITLE
Inference scripts?

### ISSUE THREAD

**Issue by josephrocca** [TencentARC/HOSNeRF#2]
Hi, thank you for releasing the code!! This is an exciting project.

I'm wondering if there's an inference script which makes it easy to test this method? E.g. a script to process a video and output an artifact, and then a second script to use the artifact + camera position to output an image?

Also, apologies if this is documented somewhere, but roughly how long does the video processing take on an A100 or similar? And also rendering an image based on the processed video artifact?

**Comment by Jia-Wei-Liu** [comment]
Hi, Thanks much for your kind words!

To align with the pytorch-lightning configuration, we include all inference codes in the https://github.com/TencentARC/HOSNeRF/blob/ca169704a9d965e8266c034cceb506ffba72f405/3rd_Complete_HOSNeRF/src/model/mipnerf360/model.py#L643

To run the inference codes, please add --resume_training True at the end of training script. It will automatically run the test / inference codes.

Regarding the inference time, it takes about 75 seconds to render one image with 1280*720 resolution on a single V100 GPU.

Hope that helps!

**Comment by josephrocca** [comment]
Thank you very much!
