### ISSUE TITLE
Flow Format of HOSNerf dataset

### ISSUE THREAD

**Issue by LzqInsta** [TencentARC/HOSNeRF#4]
Thank you for releasing the code!
I'd like to train HOSNerf on the released dataset but I found no description about flow file format.
What is the correct flow file format & file name generated by RAFT?

**Comment by Jia-Wei-Liu** [comment]
Hi, the file format is the default config of RAFT. The file name is %5d_fwd.npz or %5d_bwd.npz, e.g., 00001_fwd.npz. The flow files are large so I did not upload them. Hope that clarifies!

**Comment by oferidan1** [comment]
Hi, thanks alot for your feedback.
I tried generating the RAFT flow files using raft demo code (I made few modifications to save it in the file names your code expects).
However, when I try to load the flow files in your step 2, it fails to load the flow files, the code tries to load "flow" and "mask" parameters while RAFT output doesn't have this information. The code fails on:
bwd_flow, bwd_mask = bwd_data['flow'], bwd_data['mask']
Can you please explain how to export these parameters? (a code example would be great!).
Thanks,
Ofer

here'y my RAFT flow generation code:

        flow_prev = None
        frame = 0
        images = sorted(images)
        for imfile1, imfile2 in zip(images[:-1], images[1:]):
            image1 = load_image(imfile1)
            image2 = load_image(imfile2)

            padder = InputPadder(image1.shape)
            image1, image2 = padder.pad(image1, image2)

            flow_low, flow_pr = model(image1, image2, iters=iters, flow_init=flow_prev, test_mode=True)
            flow = padder.unpad(flow_pr[0]).permute(1, 2, 0).cpu().numpy()

            #if warm_start:
            #    flow_prev = forward_interpolate(flow_low[0])[None].cuda()

            output_file = os.path.join(output_dir, '%05d_bwd.npz' % (frame + 1))
            frame_utils.writeFlow(output_file, flow)

            frame += 1

**Comment by LzqInsta** [comment]
the mask may be the optical forward-backward consistency mask. And the flow should be backward flow, that is, flow from image2 to image1

**Comment by oferidan1** [comment]
Hi, thanks again.
Just to make sure I understand correctly - you mean that I can use the "up_mask" from raft code (code below)?
Thanks.

 with autocast(enabled=self.args.mixed_precision):
                net, **up_mask**, delta_flow = self.update_block(net, inp, corr, flow)

**Comment by LzqInsta** [comment]
No, the optical forward-backward consistency mask is computed from forward flow(from image1 to image2) and backward flow(from image2 to image1). Such mask can filter pixels with large prediction error. 
 [unimatch code](https://github.com/autonomousvision/unimatch/blob/0dfa3616d89790ac3bac3810dcdedf691b40dfdd/unimatch/geometry.py#L75) is an example to compute such a mask
