### ISSUE TITLE
Checkpoints for HOSNeRF datasets

### ISSUE THREAD

**Issue by lxxue** [TencentARC/HOSNeRF#5]
Hi, thank you for the nice work.

I wonder if you can provide the trained checkpoints for the 6 sequences so we can run inference directly?

**Comment by Jia-Wei-Liu** [comment]
Hi, I provided the checkpoints on the repo before. They were on: https://drive.google.com/drive/folders/15I7z7qjBL6rQ3z91_rzhR284L1vfxxOX

Hope that clarifies!

**Comment by lxxue** [comment]
Ah thank you for the reply. Sorry I miss that part in the readme.
